// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuNqpLkcKn6YF_RSZnrHBWqH3LP_6EpAY',
    appId: '1:922877728809:web:ed3645b393d1ff57b62438',
    messagingSenderId: '922877728809',
    projectId: 'cg-project-84269',
    authDomain: 'cg-project-84269.firebaseapp.com',
    storageBucket: 'cg-project-84269.firebasestorage.app',
    measurementId: 'G-PK7ZBQJGKX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAan7JIKjHYnVfhhcXL7bdl4RMGcXpjq-k',
    appId: '1:922877728809:android:57358414a841d5e5b62438',
    messagingSenderId: '922877728809',
    projectId: 'cg-project-84269',
    storageBucket: 'cg-project-84269.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlIqr_Saukdzt4sB03yYGvHPlC5Muclj0',
    appId: '1:922877728809:ios:3dfd3a805ac7cb7db62438',
    messagingSenderId: '922877728809',
    projectId: 'cg-project-84269',
    storageBucket: 'cg-project-84269.firebasestorage.app',
    iosBundleId: 'com.example.projektCg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlIqr_Saukdzt4sB03yYGvHPlC5Muclj0',
    appId: '1:922877728809:ios:3dfd3a805ac7cb7db62438',
    messagingSenderId: '922877728809',
    projectId: 'cg-project-84269',
    storageBucket: 'cg-project-84269.firebasestorage.app',
    iosBundleId: 'com.example.projektCg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuNqpLkcKn6YF_RSZnrHBWqH3LP_6EpAY',
    appId: '1:922877728809:web:3d0a030e68d9bec6b62438',
    messagingSenderId: '922877728809',
    projectId: 'cg-project-84269',
    authDomain: 'cg-project-84269.firebaseapp.com',
    storageBucket: 'cg-project-84269.firebasestorage.app',
    measurementId: 'G-2EYGWLMWTE',
  );
}
